stages:
  - Build
  - Deploy

.only:main:
  only:
    # v0.0.1 | v0.0.1-main | v0.0.1-stable | v0.0.1-st
    - /v\d+\.\d+\.\d+?$/
    - /v\d+\.\d+\.\d+(-main*|-stable*|-st*)(\.\d+)?$/

.build_image:
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - docker login
        -u $CI_REGISTRY_USER
        -p $CI_REGISTRY_PASSWORD
        registry.gitlab.com
  script:
    - docker build $BUILD_CONTEXT
        --file $BUILD_FILE
        --tag $TAG
        $EXTRA_ARGS
  after_script:
    - docker push $TAG


build_image:mlflow:
  stage: Build
  variables:
    IMAGE_TAG: mlflow
    TAG: $CI_REGISTRY_IMAGE/$IMAGE_TAG:$CI_COMMIT_TAG
    BUILD_FILE: Dockerfile
    BUILD_CONTEXT: .
  extends:
    - .build_image
    - .only:main